In [1]:
# ML Model for IP Analyses - Part 3
# Combining CSV's / Further Cleaning

# Importing Libraries for ML
import pandas as pd

import os
import glob

In [2]:
# Path to Files
clean_path = "D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Jupyter/imported_data/cleaned_csv"

# Combining CSV's

In [3]:
os.chdir(clean_path)
os.listdir()

['bad_url.csv',
 'dga_clean.csv',
 'phish_clean.csv',
 'to_join',
 'url_haus_clean.csv']

In [4]:
# Importing Clean DGA
dga_clean = pd.read_csv('dga_clean.csv')
dga_clean.head()

   Unnamed: 0               domain                              URL  Threat
0           0        aabebtdpa.com        https://www.aabebtdpa.com       1
1           1  aabebtdpa.pages.dev  https://www.aabebtdpa.pages.dev       1
2           2         aabebtdpa.tk         https://www.aabebtdpa.tk       1
3           3        aabtpadeb.com        https://www.aabtpadeb.com       1
4           4  aabtpadeb.pages.dev  https://www.aabtpadeb.pages.dev       1

In [5]:
# Dropping Columns in DGA
dga_clean = dga_clean.drop(columns=['Unnamed: 0', 'domain'])
dga_clean.head()

                               URL  Threat
0        https://www.aabebtdpa.com       1
1  https://www.aabebtdpa.pages.dev       1
2         https://www.aabebtdpa.tk       1
3        https://www.aabtpadeb.com       1
4  https://www.aabtpadeb.pages.dev       1

In [6]:
dga_size = dga_clean.shape
print(dga_size)

(179245271, 2)

In [7]:
dga_clean = dga_clean.sample(frac=.20).reset_index(drop=True)

In [8]:
new_dga_size = dga_clean.shape
print(new_dga_size)

(35849054, 2)

In [27]:
# Importing Clean URLhaus
url_haus_clean = pd.read_csv('url_haus_clean.csv')
url_haus_clean.head()

   Unnamed: 0                                                URL  Threat
0           0  https://orbital-velocity.fit/98a1df5c-d42b-420...       1
1           1                      http://182.126.118.95:55238/i       1
2           2                   http://115.53.56.76:36157/bin.sh       1
3           3                 http://182.126.118.14:44797/bin.sh       1
4           4                       http://110.36.74.148:49905/i       1

In [28]:
# Dropping Columns in URLhaus
url_haus_clean = url_haus_clean.drop(columns=['Unnamed: 0'])
url_haus_clean.head()

                                                 URL  Threat
0  https://orbital-velocity.fit/98a1df5c-d42b-420...       1
1                      http://182.126.118.95:55238/i       1
2                   http://115.53.56.76:36157/bin.sh       1
3                 http://182.126.118.14:44797/bin.sh       1
4                       http://110.36.74.148:49905/i       1

In [ ]:
# Importing Clean Kaggle Data

In [17]:
# Importing Bad URL
bad_url_clean = pd.read_csv('bad_url.csv')
bad_url_clean.head()

,Unnamed: 0,url,Type,Threat
0,0,https://exodsu-wallet.pages.dev,phish,1
1,1,https://manage-exods-web.pages.dev,phish,1
2,2,https://accessible-channels-814442.framer.app/,phish,1
3,3,https://pay.ontransacao.online/jqor32bqzo03vj5...,phish,1
4,4,http://allegrolokalnie.pl-oferta82106556612536...,phish,1

In [18]:
# Dropping Columns in Bad URL
bad_url_clean = bad_url_clean.drop(columns=['Unnamed: 0', 'Type'])
bad_url_clean = bad_url_clean.rename(columns={'url': 'URL'})
bad_url_clean.head()

                                                 URL  Threat
0                    https://exodsu-wallet.pages.dev       1
1                 https://manage-exods-web.pages.dev       1
2     https://accessible-channels-814442.framer.app/       1
3  https://pay.ontransacao.online/jqor32bqzo03vj5...       1
4  http://allegrolokalnie.pl-oferta82106556612536...       1

In [19]:
# Importing Phish
phish_clean = pd.read_csv('phish_clean.csv')
phish_clean.head()

,Unnamed: 0,URL,Type,Threat
0,0,nobell.it/70ffb52d079109dca5664cce6f317373782/...,Phish,1
1,1,www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...,Phish,1
2,2,serviciosbys.com/paypal.cgi.bin.get-into.herf....,Phish,1
3,3,mail.printakid.com/www.online.americanexpress....,Phish,1
4,4,thewhiskeydregs.com/wp-content/themes/widescre...,Phish,1

In [20]:
# Dropping Columns in Phish
phish_clean = phish_clean.drop(columns=['Unnamed: 0', 'Type'])
bad_url_clean.head()

                                                 URL  Threat
0                    https://exodsu-wallet.pages.dev       1
1                 https://manage-exods-web.pages.dev       1
2     https://accessible-channels-814442.framer.app/       1
3  https://pay.ontransacao.online/jqor32bqzo03vj5...       1
4  http://allegrolokalnie.pl-oferta82106556612536...       1

In [29]:
if not os.path.isdir('to_join'):
    print('to_join directory not found')
    print('Making to_join directory')
    os.mkdir('to_join')
else:
    print('to_join exists')

to_join exists

In [9]:
os.chdir(clean_path + '/to_join')
os.listdir()

['bad_url.csv',
 'cisco.csv',
 'combined',
 'dga.csv',
 'kaggle.csv',
 'majestic.csv',
 'phish.csv',
 'url_haus.csv']

In [10]:
dga_clean.to_csv('dga.csv')

In [32]:
url_haus_clean.to_csv('url_haus.csv')

In [33]:
bad_url_clean.to_csv('bad_url.csv')

In [34]:
phish_clean.to_csv('phish.csv')

In [35]:
os.listdir()

['bad_url.csv', 'dga.csv', 'phish.csv', 'url_haus.csv']

### Adding Good CSV

In [3]:
good_csv_path = "D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Jupyter/imported_data/good_csv"
os.chdir(good_csv_path)

In [4]:
os.getcwd()

'D:\\Users\\Nyk\\NCI\\OneDrive - National College of Ireland\\NCI\\Year 4\\3 Final Year Project\\S3\\0. Deliverables\\Final Submission (AUG 3)\\2. Code\\ML Building\\Jupyter\\imported_data\\good_csv'

In [5]:
os.listdir()

['cisco.csv', 'kaggle_balanced.csv', 'majestic.csv']

In [6]:
cisco = pd.read_csv('cisco.csv')

In [7]:
cisco.head()

   ID              Domain                             URL
0   1          google.com          https://www.google.com
1   2         gstatic.com         https://www.gstatic.com
2   3      www.google.com          https://www.google.com
3   4       microsoft.com       https://www.microsoft.com
4   5  data.microsoft.com  https://www.data.microsoft.com

In [11]:
# Dropping ID and Domain columns
cisco = cisco.drop(columns={'ID', 'Domain'})
cisco.head()

                              URL
0          https://www.google.com
1         https://www.gstatic.com
2          https://www.google.com
3       https://www.microsoft.com
4  https://www.data.microsoft.com

In [8]:
kaggle_balanced = pd.read_csv('kaggle_balanced.csv')

In [9]:
kaggle_balanced.head()

                         url
0     https://www.google.com
1    https://www.youtube.com
2   https://www.facebook.com
3      https://www.baidu.com
4  https://www.wikipedia.org

In [12]:
# Renaming url to URL
kaggle_balanced = kaggle_balanced.rename(columns={'url': 'URL'})
kaggle_balanced.head()

                         URL
0     https://www.google.com
1    https://www.youtube.com
2   https://www.facebook.com
3      https://www.baidu.com
4  https://www.wikipedia.org

In [10]:
majestic = pd.read_csv('majestic.csv')
majestic.head()

          Domain                        URL
0     google.com     https://www.google.com
1   facebook.com   https://www.facebook.com
2    youtube.com    https://www.youtube.com
3  instagram.com  https://www.instagram.com
4    twitter.com    https://www.twitter.com

In [13]:
# Dropping Domain column
majestic = majestic.drop(columns={'Domain'})
majestic.head()

                         URL
0     https://www.google.com
1   https://www.facebook.com
2    https://www.youtube.com
3  https://www.instagram.com
4    https://www.twitter.com

In [14]:
# Adding Threat Columns
def add_threat_column(data_frame):
    print('Adding Threat Column')
    data_frame['Threat'] = 0
    print('Finished')

In [18]:
# Adding for Cisco
add_threat_column(cisco)
cisco.head()

Adding Threat Column
Finished

                              URL  Threat
0          https://www.google.com       0
1         https://www.gstatic.com       0
2          https://www.google.com       0
3       https://www.microsoft.com       0
4  https://www.data.microsoft.com       0

In [19]:
# Adding for Kaggle_Balanced
add_threat_column(kaggle_balanced)
kaggle_balanced.head()

Adding Threat Column
Finished

                         URL  Threat
0     https://www.google.com       0
1    https://www.youtube.com       0
2   https://www.facebook.com       0
3      https://www.baidu.com       0
4  https://www.wikipedia.org       0

In [20]:
# Adding for Majestic
add_threat_column(majestic)
majestic.head()

Adding Threat Column
Finished

                         URL  Threat
0     https://www.google.com       0
1   https://www.facebook.com       0
2    https://www.youtube.com       0
3  https://www.instagram.com       0
4    https://www.twitter.com       0

In [24]:
# Saving to to_join
os.chdir(clean_path + '/to_join/')

In [25]:
cisco.to_csv('cisco.csv')
kaggle_balanced.to_csv('kaggle.csv')
majestic.to_csv('majestic.csv')

In [26]:
os.listdir()

['bad_url.csv',
 'cisco.csv',
 'dga.csv',
 'kaggle.csv',
 'majestic.csv',
 'phish.csv',
 'url_haus.csv']

### Joining

In [11]:
os.chdir(clean_path + '/to_join/')
os.getcwd()

'D:\\Users\\Nyk\\NCI\\OneDrive - National College of Ireland\\NCI\\Year 4\\3 Final Year Project\\S3\\0. Deliverables\\Final Submission (AUG 3)\\2. Code\\ML Building\\Jupyter\\imported_data\\cleaned_csv\\to_join'

In [12]:
files = '*.csv'
joined_list = glob.glob(files)
combined = pd.concat(map(pd.read_csv, joined_list), ignore_index=True)
combined.head()

   Unnamed: 0                                                URL  Threat
0           0                    https://exodsu-wallet.pages.dev       1
1           1                 https://manage-exods-web.pages.dev       1
2           2     https://accessible-channels-814442.framer.app/       1
3           3  https://pay.ontransacao.online/jqor32bqzo03vj5...       1
4           4  http://allegrolokalnie.pl-oferta82106556612536...       1

### Cleaning Combined File

In [ ]:
# Reducing Size

In [35]:
# Removing N/A
total_na = combined.isna().sum()
print(total_na) # No N/A

Unnamed: 0    0
URL           0
Threat        0
dtype: int64

In [36]:
# Removing Duplicates
total_duplicates  = combined.duplicated().sum()
print(total_duplicates)

3

In [13]:
combined = combined.drop_duplicates()

In [14]:
combined_size = combined.shape
print(combined_size)

(42638236, 3)

In [16]:
if not os.path.isdir('combined'):
    os.mkdir('combined')
os.chdir('combined')
os.getcwd()

'D:\\Users\\Nyk\\NCI\\OneDrive - National College of Ireland\\NCI\\Year 4\\3 Final Year Project\\S3\\0. Deliverables\\Final Submission (AUG 3)\\2. Code\\ML Building\\Jupyter\\imported_data\\cleaned_csv\\to_join\\combined'

In [17]:
combined.to_csv('combined.csv') # Makes a very large file still

In [15]:
# Saving as gzip instead
combined.to_csv("combined.csv.gz", index=False, compression="gzip")

In [32]:
os.getcwd()

'D:\\Users\\Nyk\\NCI\\OneDrive - National College of Ireland\\NCI\\Year 4\\3 Final Year Project\\S3\\0. Deliverables\\Final Submission (AUG 3)\\2. Code\\ML Building\\Jupyter\\imported_data\\cleaned_csv\\to_join\\combined'

# Creating a Smaller File

In [18]:
randomised_combined = combined.sample(frac=.3).reset_index(drop=True)

In [19]:
print(randomised_combined.shape)

(12791471, 3)

In [20]:
randomised_combined.head()

   Unnamed: 0                                         URL  Threat
0    30565744                     https://www.sfuwkmlb.sh       1
1    35204547                 https://www.kbtlxoxtmiq.org       1
2    11948966             https://www.okuksheubjtvuku.com       1
3    26099566  https://www.s5we541k592bp1h9zcruviipjp.net       1
4    15717922              https://www.xjilruhepfowxgq.ac       1

In [21]:
items = randomised_combined['Threat'].unique()
print(items)

[1 0]

In [22]:
num_1 = (randomised_combined['Threat'] == 1).sum()
num_0 = (randomised_combined['Threat'] == 0).sum()
print(f"Number of 1's: {num_1}")
print(f"Number of 0's: {num_0}")

Number of 1's: 12097290
Number of 0's: 694181

In [23]:
# Too many malicious examples in a data sample
print(f'Ratio Malicious/Benign samples: {num_1/num_0}')

Ratio Malicious/Benign samples: 17.426708596173043

In [24]:
# Spliting into Major and Minor
major = randomised_combined[randomised_combined['Threat'] == 1]
minor = randomised_combined[randomised_combined['Threat'] == 0]

In [25]:
major.head()

   Unnamed: 0                                         URL  Threat
0    30565744                     https://www.sfuwkmlb.sh       1
1    35204547                 https://www.kbtlxoxtmiq.org       1
2    11948966             https://www.okuksheubjtvuku.com       1
3    26099566  https://www.s5we541k592bp1h9zcruviipjp.net       1
4    15717922              https://www.xjilruhepfowxgq.ac       1

In [26]:
minor.head()

    Unnamed: 0                                                URL  Threat
6       345211                 https://www.horrornovelreviews.com       0
44      708357                https://www.online.columbiabank.com       0
57      402558                https://www.video-stal-10.mdchat.me       0
58      199649  https://www.pbipeus21-eastus2.pbidedicated.win...       0
71       60517               https://www.preferredseating.com.au/       0

In [27]:
major_size = major.shape
minor_size = minor.shape
print(major_size)
print(minor_size)

(12097290, 3)
(694181, 3)

In [28]:
major_normal_size = major.sample(n=len(minor))
major_size_fig = major_normal_size['Threat'].sum()
print(major_size_fig)

694181

In [30]:
balanced_combined = pd.concat([major_normal_size, minor]).sample(frac=1).reset_index(drop=True)

In [32]:
balanced_num_1 = (balanced_combined['Threat'] == 1).sum()
balanced_num_0 = (balanced_combined['Threat'] == 0).sum()
print(f"Number of balanced 1's: {balanced_num_1}")
print(f"Number of balanced 0's: {balanced_num_0}")

Number of balanced 1's: 694181
Number of balanced 0's: 694181

In [33]:
os.chdir('D:\\Users\\Nyk\\NCI\\OneDrive - National College of Ireland\\NCI\\Year 4\\3 Final Year Project\\S3\\0. Deliverables\\Final Submission (AUG 3)\\2. Code\\ML Building\\Jupyter\\imported_data\\cleaned_csv\\to_join\\combined')
balanced_combined.to_csv('balanced_combined.csv')