In [1]:
# ML Model for IP Analyses - Part 2
# Data Cleaning

# Importing Libraries for ML
import sklearn as sk
import pandas as pd
import numpy as np

import os

In [2]:
# CSV Location
csv_path = "D:/Users/Nyk/NCI/OneDrive - National College of Ireland/NCI/Year 4/3 Final Year Project/S3/0. Deliverables/Final Submission (AUG 3)/2. Code/ML Building/Jupyter/imported_data"
os.chdir(csv_path)

# Cleaning DGA CSV

In [ ]:
# Importing Datasets from 'imported_data'

In [3]:
# Importing DGA csv

dga = pd.read_csv('dga.csv')
dga.head()

                domain           Group
0        aabebtdpa.com  abcbot_dga.csv
1  aabebtdpa.pages.dev  abcbot_dga.csv
2         aabebtdpa.tk  abcbot_dga.csv
3        aabtpadeb.com  abcbot_dga.csv
4  aabtpadeb.pages.dev  abcbot_dga.csv

In [4]:
# General Information about DGA csv:
dga.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196852792 entries, 0 to 196852791
Data columns (total 2 columns):
 #   Column  Dtype
---  ------  -----
 0   domain  object
 1   Group   object
dtypes: object(2)
memory usage: 2.9+ GB

In [5]:
# Method for checking Duplicates:
def check_duplicates(data_frame):
    print('Starting Duplicate Check')
    try:
        if data_frame.duplicated().any():
            print('Found Duplicates')
        else:
            print('No Dupliicates Found')
    except Exception as e:
        print('Exception found in check_duplicate function')
        print(f'Exception: {e}')

In [6]:
# Cleaning DGA csv:

# 1. Looking for duplicates
check_duplicates(dga)

Starting Duplicate Check
Found Duplicates

In [ ]:
# Checking which rows are duplicated
duplicates = dga[dga.duplicated()]
print('Found Duplicates:')
print(duplicates)

In [ ]:
# Removing duplicates
dga = dga.drop_duplicates()
print('Checking Duplicates Again')
check_duplicates(dga)

In [13]:
# Getting Column Information function
def columns_type(data_frame):
    print('Starting column type check')
    
    try:
        category_column = [col for col in dga.columns if dga[col].dtype == 'object']
        number_column =  [col for col in dga.columns if dga[col].dtype != 'object']
        print(f'Category columns: {category_column}')
        print(f'Number columns: {number_column}')
    except Exception as e:
        print('Exception occured in columns_type function')
        print(f'Exception: {e}')

In [ ]:
# Checking Column Type for DGA
columns_type(dga)

In [16]:
def get_nulls(data_frame):
    print('Total nulls per column:')
    null_sum = data_frame.isnull().sum()
    print(null_sum)

In [ ]:
get_nulls(dga)

In [17]:
# Function for inserting Threat Column
def insert_threat_type(data_frame):
    try:
        print('Adding Threat Value')
        data_frame['Threat'] = 1
        print('Finished Creating Threat Column')
    except Exception as e:
        print('An exception occurred in insert_threat function')
        print(f'Exception: {e}')

In [ ]:
# Removing Unneccessary Columns
dga = dga.drop(columns=['Group'])
dga.head()

In [18]:
# Checking and Converting Domain to URL
def check_convert_domain(data_frame):
    try:
        print('Starting Check')
        has_port = data_frame['domain'].str.startswith(('https://','http://'))
        has_www = data_frame['domain'].str.startswith(('www.' 'https://www.','http://www.'))
        if has_port.any():
            print('Found Ports')
        else:
            print('Ports Not Found')
        print('Starting Conversion')
        data_frame['URL'] = data_frame['domain']
        data_frame.loc[~has_port, 'URL'] = ('https://' + data_frame.loc[~has_port, 'URL'])
        data_frame.loc[~has_www, 'URL'] =(data_frame.loc[~has_www, 'URL'].str.replace('https://','https://www.',regex=False))
        print('Conversion Finished')
    except Exception as e:
        print('Exception occurred in check_convert_domain function')
        print(f'Exception: {e}')

In [ ]:
check_convert_domain(dga)
dga.head()

In [ ]:
# Adding Threat Column to DGA
insert_threat_type(dga)

In [ ]:
dga.head()

# 2. Cleaning URLhaus CSV

In [8]:
# Importing URLhaus csv

url_haus = pd.read_csv('url.csv')
url_haus.head()

,3851096,2026-05-21 00:17:07,https://orbital-velocity.fit/98a1df5c-d42b-4208-b5c1-ab4d41d96217/zone.id,online,2026-05-21 00:17:07.1,malware_download,ClearFake,https://urlhaus.abuse.ch/url/3851096/,anonymous
0,3851095,2026-05-21 00:15:13,http://182.126.118.95:55238/i,online,2026-05-21 00:15:13,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851095/,geenensp
1,3851094,2026-05-21 00:13:19,http://115.53.56.76:36157/bin.sh,online,2026-05-21 00:13:19,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851094/,geenensp
2,3851093,2026-05-21 00:12:17,http://182.126.118.14:44797/bin.sh,online,2026-05-21 00:12:17,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851093/,geenensp
3,3851092,2026-05-21 00:02:16,http://110.36.74.148:49905/i,online,2026-05-21 00:02:16,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851092/,geenensp
4,3851091,2026-05-21 00:00:21,http://42.227.42.49:42416/bin.sh,online,2026-05-21 00:00:21,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851091/,geenensp

In [9]:
# Creating Headers for URLhaus
url_haus = pd.read_csv('url.csv', names=['ID', 'DateAdded', 'URL', 'URL_Status', 'LastOnline', 'Type', 'Tags', 'URLhaus_link', 'reporter'])
url_haus.head()

,ID,DateAdded,URL,URL_Status,LastOnline,Type,Tags,URLhaus_link,reporter
0,3851096,2026-05-21 00:17:07,https://orbital-velocity.fit/98a1df5c-d42b-420...,online,2026-05-21 00:17:07.1,malware_download,ClearFake,https://urlhaus.abuse.ch/url/3851096/,anonymous
1,3851095,2026-05-21 00:15:13,http://182.126.118.95:55238/i,online,2026-05-21 00:15:13,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851095/,geenensp
2,3851094,2026-05-21 00:13:19,http://115.53.56.76:36157/bin.sh,online,2026-05-21 00:13:19,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851094/,geenensp
3,3851093,2026-05-21 00:12:17,http://182.126.118.14:44797/bin.sh,online,2026-05-21 00:12:17,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851093/,geenensp
4,3851092,2026-05-21 00:02:16,http://110.36.74.148:49905/i,online,2026-05-21 00:02:16,malware_download,"32-bit,elf,mips,Mozi",https://urlhaus.abuse.ch/url/3851092/,geenensp

In [10]:
# Removing Unneccessary Columns
url_haus = url_haus.drop(columns=['ID', 'DateAdded', 'URL_Status', 'LastOnline', 'Type', 'Tags', 'URLhaus_link', 'reporter'])
url_haus.head()

                                                 URL
0  https://orbital-velocity.fit/98a1df5c-d42b-420...
1                      http://182.126.118.95:55238/i
2                   http://115.53.56.76:36157/bin.sh
3                 http://182.126.118.14:44797/bin.sh
4                       http://110.36.74.148:49905/i

In [11]:
# Looking for Duplicates
check_duplicates(url_haus)

Starting Duplicate Check
No Dupliicates Found

In [14]:
# Getting Type Information for Columns
columns_type(url_haus)

Starting column type check
Category columns: ['domain', 'Group']
Number columns: []

In [19]:
# Checking for N/A
get_nulls(url_haus)

Total nulls per column:
URL    0
dtype: int64

In [20]:
# Add Threat Column
insert_threat_type(url_haus)

Adding Threat Value
Finished Creating Threat Column

In [21]:
url_haus.head()

                                                 URL  Threat
0  https://orbital-velocity.fit/98a1df5c-d42b-420...       1
1                      http://182.126.118.95:55238/i       1
2                   http://115.53.56.76:36157/bin.sh       1
3                 http://182.126.118.14:44797/bin.sh       1
4                       http://110.36.74.148:49905/i       1

# 3. Cleaning Kaggles CSV's

In [ ]:
# Importing Kaggle csv's

In [22]:
# 1. Getting Phishing csv
phish = pd.read_csv('phish.csv')
phish.head()

                                                 URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

In [23]:
# Adding Extra Column
phish['Type'] = 'Phish'
phish.head()

                                                 URL Label   Type
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad  Phish
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad  Phish
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad  Phish
3  mail.printakid.com/www.online.americanexpress....   bad  Phish
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad  Phish

In [24]:
phish = phish.drop(columns=['Label'])
phish.head()

                                                 URL   Type
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...  Phish
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...  Phish
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....  Phish
3  mail.printakid.com/www.online.americanexpress....  Phish
4  thewhiskeydregs.com/wp-content/themes/widescre...  Phish

In [25]:
# Checking for Duplicates
check_duplicates(phish)

Starting Duplicate Check
Found Duplicates

In [26]:
# Removing duplicates
phish = phish.drop_duplicates()
print('Checking Duplicates at phish data_frame Again')
check_duplicates(phish)

Checking Duplicates at phish data_frame Again
Starting Duplicate Check
No Dupliicates Found

In [27]:
# Checking N/A's
get_nulls(phish)

Total nulls per column:
URL     0
Type    0
dtype: int64

In [28]:
# 2. Getting Bad URL csv
bad_url = pd.read_csv('bad_url.csv')
bad_url.head()

,Unnamed: 0,url,Type,Threat
0,0,https://exodsu-wallet.pages.dev,phish,1
1,1,https://manage-exods-web.pages.dev,phish,1
2,2,https://accessible-channels-814442.framer.app/,phish,1
3,3,https://pay.ontransacao.online/jqor32bqzo03vj5...,phish,1
4,4,http://allegrolokalnie.pl-oferta82106556612536...,phish,1

In [29]:
# Changing Column Name
bad_url = bad_url.rename(columns = {'label': 'Type'} )
bad_url.head()

,Unnamed: 0,url,Type,Threat
0,0,https://exodsu-wallet.pages.dev,phish,1
1,1,https://manage-exods-web.pages.dev,phish,1
2,2,https://accessible-channels-814442.framer.app/,phish,1
3,3,https://pay.ontransacao.online/jqor32bqzo03vj5...,phish,1
4,4,http://allegrolokalnie.pl-oferta82106556612536...,phish,1

In [30]:
# Checking for duplicates
check_duplicates(bad_url)

Starting Duplicate Check
No Dupliicates Found

In [31]:
# Checking N/A's
get_nulls(bad_url)

Total nulls per column:
Unnamed: 0    0
url           0
Type          0
Threat        0
dtype: int64

In [32]:
# Adding Threat Column
insert_threat_type(phish)
insert_threat_type(bad_url)

Adding Threat Value
Finished Creating Threat Column
Adding Threat Value
Finished Creating Threat Column

In [33]:
phish.head()

                                                 URL   Type  Threat
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...  Phish       1
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...  Phish       1
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....  Phish       1
3  mail.printakid.com/www.online.americanexpress....  Phish       1
4  thewhiskeydregs.com/wp-content/themes/widescre...  Phish       1

In [34]:
bad_url.head()

,Unnamed: 0,url,Type,Threat
0,0,https://exodsu-wallet.pages.dev,phish,1
1,1,https://manage-exods-web.pages.dev,phish,1
2,2,https://accessible-channels-814442.framer.app/,phish,1
3,3,https://pay.ontransacao.online/jqor32bqzo03vj5...,phish,1
4,4,http://allegrolokalnie.pl-oferta82106556612536...,phish,1

# Saving Cleaned CSV's

In [ ]:
# Changing Directory
os.chdir(csv_path)
os.getcwd()

In [ ]:
if os.getcwd == csv_path:
    print('Not on the imported_data directory')
else:
    print('In the imported_data directory')
    return
    
if not os.path.isdir('cleaned_csv'):
    print('cleaned_csv directory not found')
    os.mkdir('cleaned_csv')
else:
    print('Directory is found')
os.chdir(csv_path + '/cleaned_csv')
os.getcwd()

In [ ]:
# Saving DGA
dga.to_csv('dga_clean.csv')

In [ ]:
# Saving URLhaus
url_haus.to_csv('url_haus_clean.csv')

In [ ]:
# Saving Kaggle CSV's

In [ ]:
# Saving Phish CSV
phish.to_csv('phish_clean.csv')

In [ ]:
# Saving bad_url CSV
bad_url.to_csv('bad_url.csv')